# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xms10G -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+PerfDisableSharedMem -XX:ShenandoahGCMode=satb -XX:ShenandoahGCHeuristics=adaptive -XX:ShenandoahGuaranteedGCInterval=0
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.console=plain

# Environment Properties https://projects.neoforged.net/neoforged/neoforge
#I compile with:
minecraft_version=26.2
neo_version=26.2.0.32-beta

#It can work with (compatible with):
minecraft_version_range=[26.2]
neo_version_range=[26.2.0.32-beta,26.3)

## Mod Properties
mod_id=meadowandforest
mod_name=Meadow and Forest
mod_license=GPL-3.0
mod_version=0.1.0-26.2
mod_group_id=net.carqui.meadowandforest
