license="${mod_license}"
issueTrackerURL="https://github.com/bertugarangou/Meadow-and-Forest/issues"
[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/bertugarangou/Meadow-and-Forest/wiki"
logoFile="logo.png"
credits="Code made by Carqui (Albert Garangou) and art by Júlia Socoró and Carqui"
authors="Carqui (Albert Garangou)"
description='''
A Minecraft mod that adds new content for meadows, plains and forests.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
